export const ADMIN_INVITE_DEFAULT_EXPIRY_DAYS = 7;
export const ADMIN_INVITE_MAX_EXPIRY_DAYS = 30;

export const STUDENT_INVITE_DEFAULT_EXPIRY_DAYS = 30;
export const STUDENT_INVITE_MAX_EXPIRY_DAYS = 90;
